### ISSUE TITLE
[BUG] When a user belongs to both the "user" and "admin" OpenShift groups, only the user role is granted

### ISSUE THREAD

**Issue by InfoSec812** [rht-labs/sonar-auth-openshift#16]
**Do your best**

**Describe the bug**
I have SonarQube deployed on OCP 4.1. I have 2 groups mapped for users and admins. My user is member of both groups. When I log in using the OAuth plugin, only the "user" role is granted to my account within SonarQube.

**Expected behavior**
The greater privilege should be granted if both are present

**Screenshots**
N/A.

**OpenShift Version**
 - What version: 4.1
 - oc version: v4.1.10-201908061216+68e229c-dirty
 - where is OpenShift running? AWS/RHPDS

**Additional context**

**Comment by mcanoy** [comment]
I'm not able to reproduce this. I deployed the latest image from quay.io

```
$ oc get groups
NAME                      USERS
...
sonarqube_admin           developer, kmcanoy, admin2
sonarqube_user            developer, casual_user1, casual_user2, kmcanoy
```

Role Mapping from sonar.properties configmap
```
sonar.auth.openshift.sar.groups=sonarqube_admin=sonar-administrators,sonarqube_user=sonar-users
```

Login

<img width="1288" alt="Screen Shot 2020-01-07 at 10 47 25 PM" src="https://user-images.githubusercontent.com/19175449/71954207-b8507e00-31a1-11ea-90a0-533f3dfd9d48.png">

Admin enabled.

**Comment by InfoSec812** [comment]
I suspect it has to do with name ordering. Try a user group of 'auser' and an admin group of 'badmin'.

**Comment by mcanoy** [comment]
Still works. What happened when you re-ordered (the reverse of what you're asking me). Did it show admin?

Here is the debug output:

```
2020.01.09 16:43:59 DEBUG web[AW+LK/GzX46Zgt1pAABN][c.r.s.a.o.OpenShiftIdentityProvider] User response body ===== {"kind":"User","apiVersion":"user.openshift.io/v1","metadata":..."groups":["aaaasonarqube_user","labs-ci-cd-contributors","sonarqube_admin","system:authenticated","system:authenticated:oauth"]}
--
  |  
  | 2020.01.09 16:43:59 DEBUG web[AW+LK/GzX46Zgt1pAABN][c.r.s.a.o.OpenShiftIdentityProvider] Adding role sonar-administrators
  | 2020.01.09 16:43:59 DEBUG web[AW+LK/GzX46Zgt1pAABN][c.r.s.a.o.OpenShiftIdentityProvider] Adding role sonar-users
  | 2020.01.09 16:43:59 DEBUG web[AW+LK/GzX46Zgt1pAABN][c.r.s.a.o.OpenShiftIdentityProvider] Roles [sonar-users, sonar-administrators]
  | 2020.01.09 16:43:59 DEBUG web[AW+LK/GzX46Zgt1pAABN][c.r.s.a.o.OpenShiftIdentityProvider] Set user: kmcanoy
```
