### ISSUE TITLE
Add ability to deploy the plugin without using it

### ISSUE THREAD

**Issue by mcanoy** [rht-labs/sonar-auth-openshift#3]
Currently the plugin will try to initialize itself with the OpenShift env when the plugin is loaded. There should be some ability to disable the plugin without crashing sonar at start up.

I'd suggest: 

At start up - check the enabled property if it is not set or is false then do not try to load the init sequence ( check well known oauth info, find the OpenShift route, load SSL cert). Probably also log a message at load time. If enabled but one of those steps fails, throw an error and disa ble the plugin but don't crash the app.

Provide the ability to change at runtime?

**Comment by InfoSec812** [comment]
Would it be better to have it check for the existence of the `/run/secrets/kubernetes.io/serviceaccount/` files and short circuit the setup if it is not present?

**Comment by mcanoy** [comment]
Maybe. But what about the scenario where the plugin is loaded but not used. I think that's where the enabled prop comes in. Could do both.
